### ISSUE TITLE
Error with laravel 5.3

### ISSUE THREAD

**Issue by vitoo** [websmurf/laravel-cassandra#1]
Hello,

I've got this error in laravel 5.3

> Fatal error: Class 'Cassandra' not found in C:\Wnmp\html\ApiTestDev\config\cassandra.php on line 22

After installing, i got this error 

in config/app.php i've added

``` php
       /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        // App\Providers\BroadcastServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Websmurf\LaravelCassandra\CassandraServiceProvider::class,
```

`php artisan config:publish websmurf/laravel-cassandra`
This command dont work in Laravel 5.3, but anyway i've added the cassandra.php file manualy

Thanks for your help :)

**Comment by websmurf** [comment]
Hi Vitoo

As decribed in the readme file, you also need to install the Datastax php driver to be able to use my wrapper. This library is just a wrapper around the Datastax php driver to make it simple to use in Laraval and Lumen. 

You can find more information and installation instructions about the Datastax php driver on http://datastax.github.io/php-driver/

Cheers Adam

**Comment by vitoo** [comment]
Thanks, my bad

**Comment by mayur19** [comment]
Hey there i have installed the datastax php-cassandra driver but still got the error of cannot found Cassandra . Please help me out.

**Comment by websmurf** [comment]
Hi Mayur

If you are getting errors in relation to the Cassandra class not being found, that means that the php-cassandra driver is not installed correctly, or that you will need to reload php or php-fpm in order to load the newly installed driver
